language: android

env:
  matrix:
    - ANDROID_TARGET=android-22  

android:
  components:
    # needed build tools
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # extra needed components
    - extra-android-m2repository

before_script:

script: 
  - ./gradlew assembleRelease
